# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karma_player.proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0etrusttune.auth\x1a\x0c\x63ommon.proto\"\x18\n\x16GetUserIdentityRequest\"\x80\x01\n\x17GetUserIdentityResponse\x12.\n\x08identity\x18\x01 \x01(\x0b\x32\x1c.trusttune.auth.UserIdentity\x12+\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x17.trusttune.common.ErrorH\x00\x88\x01\x01\x42\x08\n\x06_error\"k\n\x0cUserIdentity\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x36\n\ncomponents\x18\x03 \x01(\x0b\x32\".trusttune.auth.UsernameComponents\"E\n\x12UsernameComponents\x12\x11\n\tadjective\x18\x01 \x01(\t\x12\x0c\n\x04noun\x18\x02 \x01(\t\x12\x0e\n\x06number\x18\x03 \x01(\x05\x32q\n\x0b\x41uthService\x12\x62\n\x0fGetUserIdentity\x12&.trusttune.auth.GetUserIdentityRequest\x1a\'.trusttune.auth.GetUserIdentityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERIDENTITYREQUEST']._serialized_start=44
  _globals['_GETUSERIDENTITYREQUEST']._serialized_end=68
  _globals['_GETUSERIDENTITYRESPONSE']._serialized_start=71
  _globals['_GETUSERIDENTITYRESPONSE']._serialized_end=199
  _globals['_USERIDENTITY']._serialized_start=201
  _globals['_USERIDENTITY']._serialized_end=308
  _globals['_USERNAMECOMPONENTS']._serialized_start=310
  _globals['_USERNAMECOMPONENTS']._serialized_end=379
  _globals['_AUTHSERVICE']._serialized_start=381
  _globals['_AUTHSERVICE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
