# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x10trusttune.common\"U\n\x05\x45rror\x12*\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1c.trusttune.common.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"2\n\x11PaginationRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"c\n\x12PaginationResponse\x12\x13\n\x0btotal_count\x18\x01 \x01(\x05\x12\x16\n\x0ereturned_count\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x12\x10\n\x08has_more\x18\x04 \x01(\x08*\xc3\x01\n\nStatusCode\x12\x1b\n\x17STATUS_CODE_UNSPECIFIED\x10\x00\x12\x12\n\x0eSTATUS_CODE_OK\x10\x01\x12\x15\n\x11STATUS_CODE_ERROR\x10\x02\x12\x19\n\x15STATUS_CODE_NOT_FOUND\x10\x03\x12\x1c\n\x18STATUS_CODE_UNAUTHORIZED\x10\x04\x12\x1c\n\x18STATUS_CODE_RATE_LIMITED\x10\x05\x12\x16\n\x12STATUS_CODE_BANNED\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSCODE']._serialized_start=320
  _globals['_STATUSCODE']._serialized_end=515
  _globals['_ERROR']._serialized_start=34
  _globals['_ERROR']._serialized_end=119
  _globals['_TIMESTAMP']._serialized_start=121
  _globals['_TIMESTAMP']._serialized_end=164
  _globals['_PAGINATIONREQUEST']._serialized_start=166
  _globals['_PAGINATIONREQUEST']._serialized_end=216
  _globals['_PAGINATIONRESPONSE']._serialized_start=218
  _globals['_PAGINATIONRESPONSE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
